package au.edu.unimelb.cis.geo.view.button;

import org.apache.batik.svggen.SVGGeneratorContext;
import org.apache.batik.svggen.SVGGraphics2D;
import org.apache.batik.svggen.SVGGraphics2DIOException;
import org.geotools.geometry.jts.ReferencedEnvelope;
import org.geotools.map.MapContent;
import org.geotools.swing.JMapFrame;
import org.geotools.swing.action.SafeAction;
import org.w3c.dom.Document;

import javax.swing.*;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.io.*;

public class ExportSVG extends SafeAction {

    private JMapFrame mapFrame;
    private MapContent map;

    public ExportSVG(JMapFrame mapFrame, MapContent map) {
        super("ExportSVG");
        putValue(Action.SHORT_DESCRIPTION, "Exports the visible map as a SVG file.");
        this.mapFrame = mapFrame;
        this.map = map;
    }

    @Override
    public void action(ActionEvent actionEvent) throws Throwable {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Specify a file to save");

        int userSelection = fileChooser.showSaveDialog(mapFrame);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();

            try {
                exportToSVG(fileToSave);
            } catch (ParserConfigurationException pe) {
                String msg = "Error:" + fileToSave.getName() + " was not exported!";
                JOptionPane.showMessageDialog(null, msg, "SVG exporting",
                        JOptionPane.ERROR_MESSAGE);
            }

//            System.out.println("INFO: Save as file: " + fileToSave.getAbsolutePath());
        }
    }

    public void exportToSVG(File file)
            throws ParserConfigurationException {

//            java.awt.Dimension canvasSize = jframe.getMapPane().getSize();
        Document doc;

        DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
        DocumentBuilder db;

        db = dbf.newDocumentBuilder();

        // Create an instance of org.w3c.dom.Document
        doc = db.getDOMImplementation().createDocument(null, "svg", null);

        // Set up the map
        SVGGeneratorContext ctx1 = SVGGeneratorContext.createDefault(doc);
        SVGGeneratorContext ctx = ctx1;
        ctx.setComment("Generated by GeoTools with Batik SVG Generator");

        SVGGraphics2D g2d = new SVGGraphics2D(ctx, true);

        g2d.setSVGCanvasSize(mapFrame.getMapPane().getSize());

        Rectangle outputArea = new Rectangle(g2d.getSVGCanvasSize());
        ReferencedEnvelope dataArea = map.getViewport().getBounds();

        mapFrame.getMapPane().getRenderer().paint(g2d, outputArea, dataArea);
        OutputStreamWriter osw = null;

        try {
            OutputStream out = new FileOutputStream(file);
            osw = null;

            osw = new OutputStreamWriter(out, "UTF-8");
            g2d.stream(osw);

        } catch (FileNotFoundException | UnsupportedEncodingException |
                SVGGraphics2DIOException ex) {
            System.err.println("IOException found: " + ex);
        } finally {
            if (osw != null) {
                try {
                    osw.close();
                } catch (IOException ex) {
                    System.err.println("IOException found: " + ex);
                }
            }
        }
    }
}
